from django.urls import path

from .views import (
    AnnouncementListCreateView,
    BatchResultExcelView,
    CourseGradeSummaryView,
    DownloadGradeTemplateView,
    ExaminationDashboardView,
    FacultyCourseSyncView,
    GradeAuditLogView,
    PreviewGradesCSVView,
    PublishResultsView,
    ReevaluationRequestView,
    ReevaluationResolveView,
    ReminderDispatchView,
    ResultPublicationStatusView,
    SeatingPlanView,
    StudentMarksheetDownloadView,
    StudentResultView,
    StudentSemesterListView,
    SubmitGradesView,
    TranscriptView,
    UpdateGradeView,
    UploadGradesCSVView,
    ValidateGradesView,
    VerifyGradesView,
)

app_name = "examination"

urlpatterns = [
    path("api/dashboard/", ExaminationDashboardView.as_view(), name="dashboard"),
    path("api/faculty/sync-registrations/", FacultyCourseSyncView.as_view(), name="sync-registrations"),
    path("api/faculty/submit-grades/", SubmitGradesView.as_view(), name="submit-grades"),
    path("api/faculty/preview-csv/", PreviewGradesCSVView.as_view(), name="preview-csv"),
    path("api/faculty/upload-csv/", UploadGradesCSVView.as_view(), name="upload-csv"),
    path("api/faculty/download-template/", DownloadGradeTemplateView.as_view(), name="download-template"),
    path("api/faculty/course-summary/", CourseGradeSummaryView.as_view(), name="course-summary"),
    path("api/dean/validate-grades/", ValidateGradesView.as_view(), name="validate-grades"),
    path("api/dean/verify-grades/", VerifyGradesView.as_view(), name="verify-grades"),
    path("api/dean/update-grade/", UpdateGradeView.as_view(), name="update-grade"),
    path("api/acad-admin/publish-results/", PublishResultsView.as_view(), name="publish-results"),
    path("api/acad-admin/publication-status/", ResultPublicationStatusView.as_view(), name="publication-status"),
    path("api/acad-admin/generate-transcript/", TranscriptView.as_view(), name="generate-transcript"),
    path("api/acad-admin/generate-result-excel/", BatchResultExcelView.as_view(), name="generate-result-excel"),
    path("api/acad-admin/announcements/", AnnouncementListCreateView.as_view(), name="announcements"),
    path("api/acad-admin/seating-plan/", SeatingPlanView.as_view(), name="seating-plan"),
    path("api/acad-admin/reminders/", ReminderDispatchView.as_view(), name="reminders"),
    path("api/student/results/semesters/", StudentSemesterListView.as_view(), name="student-semesters"),
    path("api/student/results/", StudentResultView.as_view(), name="student-results"),
    path("api/student/marksheet/", StudentMarksheetDownloadView.as_view(), name="student-marksheet"),
    path("api/student/transcript/", TranscriptView.as_view(), name="student-transcript"),
    path("api/student/reevaluation/", ReevaluationRequestView.as_view(), name="student-reevaluation"),
    path("api/reevaluation/resolve/", ReevaluationResolveView.as_view(), name="reevaluation-resolve"),
    path("api/audit-logs/", GradeAuditLogView.as_view(), name="audit-logs"),
]
